### PR TITLE
Add squash script

### PR DESCRIPTION
**Pull request by mkluczny**
@chris

### CODE REVIEW

**Comment by chris** [comment]
@mkluczny all of this already gets done when you use `ship`. `ship` calls `hack`, and then it does the interactive rebase (which allows you to squash), and then calls `finish_ship` which does the force push, etc. So, I'm not clear on the particular need or issue here - let me know.

**Comment by mkluczny** [comment]
Sometimes when I have an open branch for a couple of days I tend to squash daily to avoid conflicts at the end

**Comment by mkluczny** [comment]
It also supports squashing branch on another branch

**Comment by chris** [comment]
Ok cool. Ya, it might be good to redo the ship stuff to leverage this, but not critical. Thanks!

**Review by chris — APPROVED** [review]

**Pull request merged**
